server:
  port: 8080
---
spring:
  cloud:
    gateway:
      routes:
        - id: course
          uri: http://localhost:8081
          predicates:
            - Path=/courses/**
        - id: lecture
          uri: http://localhost:8082
          predicates:
            - Path=/lectures/**
        - id: certification
          uri: http://localhost:8083
          predicates:
            - Path=/certifications/**
        - id: payment
          uri: http://localhost:8084
          predicates:
            - Path=/payments/**
        - id: student
          uri: http://localhost:8085
          predicates:
            - Path=/students/**
